---
env:
  browser: true
  es6: true
  node: true
  jest: true
extends: airbnb
parser: babel-eslint
parserOptions:
  ecmaVersion: 6
plugins:
  - react
rules:
  no-underscore-dangle: 0
  linebreak-style: 0
  react/sort-comp: 0
  jsx-a11y/label-has-for:
    - 2
    - components:
      - Label
      required:
        some:
        - nesting
        - id
      allowChildren: false
  max-len: 0
  react/jsx-boolean-value:
    - error
    - always
  react/jsx-filename-extension:
    - warn
    - extensions: [ .js ]
  react/prefer-stateless-function: off
  react/require-default-props: off
  react/jsx-max-props-per-line:
    - 2
  comma-dangle:
    - error
    - functions: ignore
      arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
  import/no-named-as-default: off
  import/prefer-default-export: off
  newline-per-chained-call:
      - error
      - ignoreChainWithDepth: 2
  function-paren-newline: 0
  jsx-a11y/no-static-element-intercations:
    - 0
  jsx-a11y/click-events-have-key-events: off
  import/order:
      - error
      - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
        newlines-between: always
  object-curly-newline: 0
